# General Jekyll Config
pygments: true
url: http://cfn.io
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
show_drafts: true

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#3498db'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: datapolitical
    #bitbucket: philipj
    hacker_news: datapolitical
    #stackexchange: 348619
    #stackoverflow: 348619
    twitter: chrisfnicholson
    #facebook: zuck
    #tumblr: animalygifs
    #linkedin: chrisfnicholson
    #gplus: 110552447039675960964

  # "Hi, I'm _______"
  name: Chris Nicholson
  email: chris.f.nicholson@gmail.com
  tagline: "weak opinions, strongly held"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-xx

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true
